[package]
name = "tumblewede/val"
description = "A simple, lightweight state management library."
license = "MIT"
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["init.luau", "LICENSE", "wally.toml"]